services:
  php:
    build: ./docker/php
    container_name: orderly_php
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    expose:
      - 9000
    user: "1000:1000"
    # args:
    #   user_id: 1000

  nginx:
    build: ./docker/nginx
    container_name: orderly_nginx
    ports:
      - 8080:80
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - php

  mysql:
    image: mysql:8.0
    container_name: orderly_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  mysql_data:
